version: '3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - weather-db:/data/db:rw
  weather:
    image: weather:latest
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./.env:/app/dist/.env:ro
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  weather-db: